#!/usr/bin/env bash
set -euo pipefail

# Compression tool to use
compressor="pixz"

# Extension for compressed file generated by this script
output_extension=".tar.xz"

# NOTE: vcpkg saves the raw directory layout into a directory of the same name
# as passed as argument without the output extension
if [[ $1 != *"${output_extension}" ]]; then
  echo "Must provide output filename ending with '${output_extension}'"
  exit 1
fi
export_dir="${1%%${output_extension}*}"
echo "Exporting to directory: ${export_dir}"

# check for pixz for parallel xz
if ! command -v "${compressor}" &>/dev/null; then
  echo "Could not find recommended compression tool '${compressor}'"
  echo "Please install and place on PATH."
  exit
fi

echo "Using compression tool '${compressor}'"
echo ""

# Check for vcpkg directory
vcpkg_root="${PWD}/vcpkg"
if [ ! -d "${vcpkg_root}" ]; then
  echo "Could not find 'vcpkg' directory at '${PWD}'"
  exit
fi

vcpkg_exe="${vcpkg_root}/vcpkg"
if [ ! -f "${vcpkg_exe}" ]; then
  echo "Could not find 'vcpkg' executable at '${vcpkg_root}'"
  exit
fi

echo "Exporting all vcpkg packages"
# TODO: Say something about the overlay directories
# NOTE: Always saves the export output in vcpkg root
start_time="$(date +%s)"
(
  set -x
  "${vcpkg_exe}" export --x-all-installed --overlay-ports=./ports --overlay-triplets=./triplets --raw "--output=${export_dir}"
)
echo Duration: "$(($(date +%s) - start_time))s"
echo ""

echo "Compressing vcpkg packages with '${compressor}' to: ${1}"
start_time="$(date +%s)"
(
  set -x
  tar --use-compress-program "${compressor}" -cf "${1}" -C "${vcpkg_root}" "${export_dir}"
)
echo Duration: "$(($(date +%s) - start_time))s"
echo ""

echo "Cleaning up export directory"
(
  set -x
  rm -r "${vcpkg_root:?}/${export_dir}"
)
