if(DEFINED ENV{TRAILOFBITS_LIBRARIES})
  set(CXX_COMMON_REPOSITORY_ROOT $ENV{TRAILOFBITS_LIBRARIES} CACHE PATH "Location of cxx-common libraries")
endif()

if("x${CXX_COMMON_REPOSITORY_ROOT}x" STREQUAL "xx")
    message(ERROR "The TRAILOFBITS_LIBRARIES environment variable is not defined!")
endif()

list(APPEND CMAKE_MODULE_PATH "${CXX_COMMON_REPOSITORY_ROOT}/cmake_modules")

list(APPEND CMAKE_PREFIX_PATH "${CXX_COMMON_REPOSITORY_ROOT}/gflags")
list(APPEND CMAKE_PREFIX_PATH "${CXX_COMMON_REPOSITORY_ROOT}/llvm")
list(APPEND CMAKE_PREFIX_PATH "${CXX_COMMON_REPOSITORY_ROOT}/glog")
list(APPEND CMAKE_PREFIX_PATH "${CXX_COMMON_REPOSITORY_ROOT}/protobuf/lib/cmake/protobuf")
list(APPEND CMAKE_PREFIX_PATH "${CXX_COMMON_REPOSITORY_ROOT}/capnproto/lib/cmake/CapnProto")

if(EXISTS "${CXX_COMMON_REPOSITORY_ROOT}/boost")
  set(BOOST_ROOT "${CXX_COMMON_REPOSITORY_ROOT}/boost")
endif()
