name: Docker Build Images (AMD64)

on:
  schedule:
    # Once every Wednesday at 00:00
    - cron: '0 0 * * 3'
  push:
    branches:
      - master
    paths:
      - 'docker/**'
      - '.github/workflows/vcpkg_docker_amd64.yml'
  pull_request:
    paths:
      - 'docker/**'
      - '.github/workflows/vcpkg_docker_amd64.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # arch is to tag docker images for uniqueness
        host:
          - { name: 'ubuntu-20.04', arch: '' }
        container:
          - { distro: 'ubuntu', version: '20.04', codename: 'focal' }
          - { distro: 'ubuntu', version: '22.04', codename: 'jammy' }

    runs-on: ${{ matrix.host.name }}

    steps:
      - name: Cleanup working directory with container root
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace ubuntu:latest find . -name . -o -prune -exec rm -rf -- {} + || true
      - uses: actions/checkout@v3
      - name: Build and Push
        working-directory: docker
        run: |
          # Pull freshest ubuntu Docker image
          docker pull ubuntu:${{ matrix.container.version}}

          docker build -f Dockerfile.ubuntu.vcpkg --target caching --no-cache --build-arg "DISTRO_VERSION=${{ matrix.container.codename }}" -t "docker.pkg.github.com/${DOCKER_TAG}" .
          # Docker image with NuGet support goes to github packages for CI use only
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]] ; then
            docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
            for i in 1 2 3; do docker push "docker.pkg.github.com/${DOCKER_TAG}" && break || sleep 10; done
          fi

          # NOTE: Docker Hub only allows one slash in tag
          docker build -f Dockerfile.ubuntu.vcpkg --target base --build-arg "DISTRO_VERSION=${{ matrix.container.codename }}" -t "trailofbits/cxx-common-vcpkg-builder-${{ matrix.container.distro }}:${{ matrix.container.version }}${{ matrix.host.arch }}" .
          # Smaller Docker image without NuGet support goes to Docker Hub for users
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]] ; then
            docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_TOKEN}"
            for i in 1 2 3; do docker push "trailofbits/cxx-common-vcpkg-builder-${{ matrix.container.distro }}:${{ matrix.container.version }}${{ matrix.host.arch }}" && break || sleep 10; done
          fi
        env:
          DOCKER_TAG: lifting-bits/cxx-common/vcpkg-builder-${{ matrix.container.distro }}:${{ matrix.container.version }}${{ matrix.host.arch }}
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{  secrets.GITHUB_PACKAGE_REGISTRY_TOKEN  }}
          DOCKER_HUB_USER: ${{  secrets.DOCKER_HUB_USER  }}
          DOCKER_HUB_TOKEN: ${{  secrets.DOCKER_HUB_TOKEN  }}
