on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  release:
    name: Publish Release on GitHub
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'rc') }}
        token: ${{ secrets.RELEASE_TOKEN }}
