name: Docker Build Images (AMD64)

env:
  IMAGE_VER: "v2"

on:
  schedule:
    # Once every Wednesday at 00:00
    - cron: '0 0 * * 3'
  push:
    branches:
      - master
    paths:
      - 'docker/**'
      - '.github/workflows/vcpkg_docker_amd64.yml'
  pull_request:
    paths:
      - 'docker/**'
      - '.github/workflows/vcpkg_docker_amd64.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # arch is to tag docker images for uniqueness
        host:
          - { name: 'ubuntu-22.04', arch: '' }
        container:
          - { version: '20.04', codename: 'focal' }
          - { version: '22.04', codename: 'jammy' }

    runs-on: ${{ matrix.host.name }}

    steps:
      - name: Cleanup working directory with container root
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace ubuntu:latest find . -name . -o -prune -exec rm -rf -- {} + || true
      - uses: actions/checkout@v3
      - name: Generate Image Name
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          test_name=""
          if [[ "${GITHUB_REF}" != "refs/heads/master" ]] ; then
            test_name="test-${BRANCH_NAME////_}-"
          fi
          echo "IMAGE_NAME=${test_name}vcpkg-builder-ubuntu-${{ env.IMAGE_VER }}:${{ matrix.container.version }}${{ matrix.host.arch }}" >> ${GITHUB_ENV}

      - name: Build and Push
        working-directory: docker
        run: |
          # Pull freshest ubuntu Docker image
          docker pull ubuntu:${{ matrix.container.version}}

          # Build for GitHub Actions registry
          # Docker image with NuGet support goes to github packages for CI use only
          DOCKER_TAG="docker.pkg.github.com/lifting-bits/cxx-common/${IMAGE_NAME}"
          docker build -f Dockerfile.ubuntu.vcpkg --no-cache \
              --target caching \
              --build-arg "DISTRO_VERSION=${{ matrix.container.codename }}" \
              -t "${DOCKER_TAG}" \
              .
          docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
          for i in 1 2 3; do docker push "${DOCKER_TAG}" && break || sleep 10; done

          # NOTE: Docker Hub only allows one slash in tag
          # DOCKER_TAG="trailofbits/cxx-common-${IMAGE_NAME}"
          # docker build -f Dockerfile.ubuntu.vcpkg --target base --build-arg "DISTRO_VERSION=${{ matrix.container.codename }}" -t "${DOCKER_TAG}" .
          # Smaller Docker image without NuGet support goes to Docker Hub for users
          #if [[ "${GITHUB_REF}" == "refs/heads/master" ]] ; then
          #  docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_TOKEN}"
          #  for i in 1 2 3; do docker push "${DOCKER_TAG}" && break || sleep 10; done
          #fi
        env:
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{  secrets.GITHUB_PACKAGE_REGISTRY_TOKEN  }}
          # DOCKER_HUB_USER: ${{  secrets.DOCKER_HUB_USER  }}
          # DOCKER_HUB_TOKEN: ${{  secrets.DOCKER_HUB_TOKEN  }}
