name: MacOS Continuous Integration

env:
  # "Source" is set in the setup-dotnet action
  VCPKG_BINARY_SOURCES: 'clear;nuget,Source,readwrite;nugettimeout,3601'
  TRIPLET: 'x64-osx-rel'
  VCPKG_DEFAULT_HOST_TRIPLET: 'x64-osx-rel'

on:
  release:
    types:
      - published
  pull_request:
    paths-ignore:
      - 'docker/**'
      - '.github/**'
      - '**.md'
      - 'old/**'
      - '!.github/workflows/vcpkg_ci_mac.yml'
  push:
    paths-ignore:
      - 'docker/**'
      - '.github/**'
      - '**.md'
      - 'old/**'
      - '!.github/workflows/vcpkg_ci_mac.yml'
    tags-ignore:
      - 'v*'
    branches:
      - 'master'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - { runner: 'macos-11', xcode: '13.0' }
        llvm: [
          'llvm-12',
          'llvm-13'
          ]

    runs-on: ${{ matrix.os.runner }}

    env:
      ARTIFACT_NAME: vcpkg_${{ matrix.os.runner }}_${{ matrix.llvm }}_xcode-${{ matrix.os.xcode }}_amd64.tar.xz

    steps:
      # Used to get commit message since PRs are on a merge commit
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.event.after }}
          submodules: false
      - name: Get commit message
        run: |
          echo 'COMMIT_MESSAGE<<EOF' >> "$GITHUB_ENV"
          echo "$(git log --format=%B -n 1 ${{ github.event.after }})" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

      - uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '3.1.x' # SDK Version to use.
          # Sets as "Source"
          source-url: https://nuget.pkg.github.com/lifting-bits/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Select the XCode version
        run: |
          echo "Selecting XCode Version ${{ matrix.os.xcode }}"
          sudo xcode-select -s /Applications/Xcode_${{ matrix.os.xcode }}.app/Contents/Developer

      - name: Read vcpkg Info
        id: vcpkg_info
        shell: bash
        run: |
          { read -r vcpkg_repo_url && read -r vcpkg_commit; } <./vcpkg_info.txt || exit 1
          echo ::set-output name=repo_url::${vcpkg_repo_url}
          echo ::set-output name=commit::${vcpkg_commit}

        # Needed for caching the actual vcpkg executable
      - name: 'Restore from cache and install vcpkg'
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitURL: ${{ steps.vcpkg_info.outputs.repo_url }}
          vcpkgGitCommitId: ${{ steps.vcpkg_info.outputs.commit }}
          appendedCacheKey: '${{ matrix.os.runner }}-${{ matrix.os.xcode }}-${{ matrix.llvm }}-clear'
          setupOnly: true

        # Omit this step if using manifests
      - name: 'vcpkg install dependencies'
        shell: 'bash'
        run: |
          # Setup NuGet authentication
          mono "$(${VCPKG_ROOT}/vcpkg fetch nuget | tail -n 1)" setapikey \
            -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            "${{ secrets.GITHUB_TOKEN }}"

          ${VCPKG_ROOT}/vcpkg install \
            --triplet "${TRIPLET}" \
            --clean-after-build \
            --debug \
            ${{ matrix.llvm }} \
            @overlays.txt \
            @dependencies.txt

      - name: 'Export Packages'
        if: contains(env.COMMIT_MESSAGE, 'debug artifacts') || github.event.release
        shell: 'bash'
        run: |
          brew install pixz
          ./emit_artifacts.sh ${{ env.ARTIFACT_NAME }}

      - uses: actions/upload-artifact@v2.3.1
        if: contains(env.COMMIT_MESSAGE, 'debug artifacts') || github.event.release
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}

      - name: 'Install build dependencies'
        shell: 'bash'
        run: |
          brew install ninja ccache

      - name: Prepare ccache
        id: ccache_prep
        shell: bash
        run: |
          echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
          echo "CCACHE_COMPILERCHECK=content" >> $GITHUB_ENV
          echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
          echo "CMAKE_C_COMPILER_LAUNCHER=$(which ccache)" >> $GITHUB_ENV
          echo "CMAKE_CXX_COMPILER_LAUNCHER=$(which ccache)" >> $GITHUB_ENV
          echo ::set-output name=timestamp::$(python -c 'from datetime import datetime; print(datetime.utcnow().strftime("%Y-%m-%d-%H:%M:%S"))')

      - name: ccache cache files
        uses: actions/cache@v2.1.7
        with:
          path: ${{  github.workspace }}/.ccache
          key: ccache-${{ matrix.os.runner }}-${{ matrix.os.xcode }}-${{ matrix.llvm }}-${{ steps.ccache_prep.outputs.timestamp }}
          restore-keys: |
            ccache-${{ matrix.os.runner }}-${{ matrix.os.xcode }}-${{ matrix.llvm }}-

      - name: ccache Initial stats
        shell: bash
        run: |
          ccache --show-stats

      - name: 'Rellic build'
        shell: 'bash'
        if: ${{ matrix.llvm == 'llvm-12' }}
        run: |
          cd rellic
          mkdir -p build && cd build
          cmake -G Ninja \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DVCPKG_ROOT="${VCPKG_ROOT}" \
            -DCMAKE_INSTALL_PREFIX="$(pwd)/install" \
            ..
          cmake --build .
          cmake --build . --target install
          ../scripts/roundtrip.py ./tools/rellic-decomp-* ../tests/tools/decomp "${VCPKG_ROOT}/installed/${TRIPLET}/tools/llvm/clang"

      - name: 'Remill build'
        shell: 'bash'
        if: ${{ matrix.llvm == 'llvm-12' }}
        run: |
          cd remill
          mkdir -p build && cd build
          cmake -G Ninja \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DVCPKG_ROOT="${VCPKG_ROOT}" \
            -DCMAKE_INSTALL_PREFIX="$(pwd)/install" \
            ..
          cmake --build .
          cmake --build . --target install
          cmake --build . --target test_dependencies
          # Sometimes fails on a flaky test
          env CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --target test || true

      - name: 'Anvill build'
        shell: 'bash'
        if: ${{ matrix.llvm == 'llvm-12' }}
        run: |
          cd anvill
          mkdir -p build && cd build
          cmake -G Ninja \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DCMAKE_INSTALL_PREFIX="$(pwd)/install" \
            -DVCPKG_ROOT="${VCPKG_ROOT}" \
            -DANVILL_ENABLE_INSTALL_TARGET=ON \
            -DANVILL_ENABLE_PYTHON3_LIBS=OFF \
            -Dremill_DIR="$(pwd)/../../remill/build/install/lib/cmake/remill" \
            ..
          cmake --build .
          cmake --build . --target install
          ./install/bin/anvill-decompile-json-* -spec ../tools/decompile-json/tests/specs/ret0.json -bc_out ./ret0.bc -ir_out ret0.ir

      - name: Publish Release Assets
        if: |
          github.event.release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARTIFACT_NAME }}
          prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'rc') }}
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Cache cleanup and reporting
        shell: 'bash'
        run: |
          rm -rf ${VCPKG_ROOT}/{buildtrees,installed,packages}
          ccache --show-stats
